api_version = "2026-04"

[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
handle = "home-review-app"
type = "ui_extension"
uid = "973c68a7-28f9-2b3a-05cf-bab2da648d989cb9105a"

# Only 1 target can be specified for each app-home extension
[[extensions.targeting]]
module = "./src/AppHome.jsx"
target = "admin.app.home.render"
assets = "./assets"
